# Generated by Django 5.2.12 on 2026-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller/ผู้ขาย'), ('farmer', 'Farmer/ผู้ขาย (เดิม)'), ('customer', 'Customer/ผู้ซื้อ'), ('buyer', 'Buyer/ผู้ซื้อ (เดิม)'), ('admin', 'Admin')], default='buyer', max_length=10),
        ),
    ]
