# Generated by Django 5.2.12 on 2026-05-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_product_name_orderitem_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('confirmed', 'ยืนยันแล้ว'), ('preparing', 'กำลังเตรียม'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'ได้รับสินค้า'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
