# Generated by Django 5.2.12 on 2026-05-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_preparing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
